export const UNDER_THE_SEA_STYLE = {
    '--button-color': '#8faea9',
    '--button-color-disabled': '#cadbd8',
    '--button-hover-color': '#a1c3bd',
    '--button-border': '#547078',
    '--button-font-color': '#000000',
    '--button-disabled-border-color': '#8faea9',
    '--button-disabled-color': '#8faea9',
    '--button-disabled-font-color': '#828282',
    '--clearer-button-color': '#8faea9',
    '--clearer-button-hover-color': '#a1c3bd',
    '--quit-button-color': '#ba614d',
    '--quit-button-hover-color': '#814c40',
    '--quit-button-border-color': '#000000',
    '--arrow-button-color': '#000000',
    '--arrow-button-border-color': '#000000',
    '--easy-button-selected-color': '#43cc40',
    '--easy-button-color': '#3bb539',
    '--easy-button-border-color': '#0e8c0b',
    '--hard-button-selected-color': '#ee6161',
    '--hard-button-color': '#d25656',
    '--hard-button-border-color': '#a81e1e',
    '--bad-button-color': '#e00000',
    '--bad-button-hover-color': '#a81212',
    '--play-button-color': '#3fd258',
    '--play-button-border-color': '#33a947',
    '--play-button-hover-color': '#3ab04e',

    '--overlay-background-color': '#ddedea',
    '--overlay-border-color': '#547078',
    '--greying-screen-color': '#00000099',

    '--tile-border': '#8faea9',
    '--tile-color': '#5b857d',
    '--tile-font-color': '#ffffff',
    '--tile-manipulated-border': '#ff0000',
    '--tile-traded-border': '#10B010',

    '--title-color': '#4c716a',

    '--shadow-color': '#ffffff',

    '--table-font-color': '#ffffff',
    '--table-color': '#8faea9',
    '--table-border-color': '#547078',
    '--scroll-bar-background-color': '#d3ecec',

    '--input-placeholder-font-color': '#a8a8a8',
    '--input-background-color': '#547078',
    '--input-error-border-color': '#e00000',
    '--input-sending-button-hover-color': '#23dff8',
    '--input-sending-button-color': '#00bcd4',
    '--input-sending-button-border-color': '#006064',

    '--message-font-color': '#ffffff',
    '--client-message-color': '#7fd47d',
    '--system-message-color': '#000000',
    '--other-message-color': '#867964',
    '--message-sender-font-color': '#547078',
    '--message-time-font-color': '#000000',
    '--notification-color': '#ff0000',

    '--team-font-color': 'brown',

    '--seperator': '#4c716a',

    '--tooltip-color': '#a1c3bd',
    '--tooltip-border-color': '#8faea9',
    '--error-tooltip-border-color': '#680707',

    '--turn-color': '#25af25',
    '--chat-background-color': '#badfdd',
    '--easel-border-color': '#e1e0e0',
    '--easel-color': '#ffffff',

    '--warning-font-color': '#e00000',
    '--error-font-color': '#ff0000',

    '--background-color': '#ddedea',
    '--general-font-color': '#547078',

    '--game-item-border-color': '#ffffff',
    '--game-item-info-color': '#ffffff',
    '--waiting-dot-color': '#badfdd',
};
